version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/prod-batch

permissions:
  - object: /home/ec2-user/prod-batch
    owner: ec2-user
    group: ec2-user
    mode: 744

hooks:
  ApplicationStart:
    - location: deploy/crontab.sh
      runas: ec2-user
    - location: deploy/env.sh
      runas: ec2-user    
