version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/prod-batch

permissions:
  - object: /home/ec2-user/prod-batch
    owner: root
    group: root
    mode: 777

hooks:
  ApplicationStart:
    - location: deploy/crontab.sh
      runas: root
    - location: deploy/env.sh
      runas: root    
